<a href="https://colab.research.google.com/github/mohammadalkhawaldah/LevelSpace/blob/master/Copy_of_Numpy_22_11_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **NUMPY TRAINING **

Monday 22 November, 2021


In [ ]:
L = [1, 2, 3]

In [ ]:
L

[1, 2, 3]

In [ ]:
import numpy as np

In [ ]:
A = np.array([1, 2,3])

In [ ]:
A

array([1, 2, 3])

In [ ]:
for zz in L:
  print(zz)

1
2
3


In [ ]:
for i in A:
  print(i)

1
2
3


In [ ]:
L

[1, 2, 3]

In [ ]:
L.append(77)
L

[1, 2, 3, 77, 77]

In [ ]:
L

[1, 2, 3, 77]

In [ ]:
z = [5 ,6 , 7]

In [ ]:
w=[]

In [ ]:
 z.append(99)
 z

[5, 6, 7, 99, 99]

In [ ]:
A

array([1, 2, 3])

In [ ]:
A.append(44)

AttributeError: ignored

In [ ]:
L 

[1, 2, 3, 77, 77]

In [ ]:
L = [ 1, 2, 3, 4]
L

[1, 2, 3, 4]

In [ ]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
L

[1, 2, 3, 4]

In [ ]:
L + [7]

[1, 2, 3, 4, 7]

In [ ]:
L + [99]

[1, 2, 3, 4, 99]

In [ ]:
L


[1, 2, 3, 4]

In [ ]:
L = L + [7]

In [ ]:
L

[1, 2, 3, 4, 7]

In [ ]:
A

array([1, 2, 3])

In [ ]:
A + np.array([5, 6, 7])

array([ 6,  8, 10])

In [ ]:
A + np.array([5, 6])

ValueError: ignored

In [ ]:
A

array([1, 2, 3])

In [ ]:
6 + A

array([7, 8, 9])

In [ ]:
L

[1, 2, 3, 4, 7]

In [ ]:
L + L

[1, 2, 3, 4, 7, 1, 2, 3, 4, 7]

In [ ]:
L

[1, 2, 3, 4, 7]

In [ ]:
A

array([1, 2, 3])

In [ ]:
L2 = []

In [ ]:
L = [1, 2, 3]
L

[1, 2, 3]

In [ ]:
for e in L:
  L2.append(e + 2) 
L2


[3, 4, 5]

In [ ]:
L2 = []
L2

[]

In [ ]:
L

[1, 2, 3]

In [ ]:
for e in L:
  L2.append(e**2)
  print(L2)


[1]
[1, 4]
[1, 4, 9]


In [ ]:
A

array([1, 2, 3])

In [ ]:
A**2

array([1, 4, 9])

In [ ]:
A

array([1, 2, 3])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
A

array([1, 2, 3])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

### **DOT PRODUCT**

In [ ]:
a= np.array( [1, 2])

In [ ]:
b = np.array([3, 4])

In [ ]:
a

array([1, 2])

In [ ]:
b

array([3, 4])

In [ ]:
dot = 0
for i in range (2):

   dot += (a[i] * b[i])

dot   




11

In [ ]:
a * b

array([3, 8])

In [ ]:
np.sum(a * b)

11

In [ ]:
a @ b

11

In [ ]:
a.dot(b)

11

In [ ]:
a

array([1, 2])

In [ ]:
a * a

array([1, 4])

In [ ]:
b

array([3, 4])

In [ ]:
m = np.sqrt((a * a).sum())

In [ ]:
m

2.23606797749979